spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

spring.cloud.stream.bindings.transactionsSupplier-out-0.destination = transactions
spring.cloud.stream.bindings.transactions-in-0.destination = transactions

spring.ksql-server.host = cp-ksql-server
spring.ksql-server.port = 8088

springwolf.docket.base-package = pl.piomin.datamesh.transactions
springwolf.docket.info.title = ${spring.application.name}
springwolf.docket.info.version = 1.0
springwolf.docket.servers.kafka.protocol = kafka
springwolf.docket.servers.kafka.url = ${spring.kafka.bootstrap-servers:localhost:9092}